version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      HOST: 0.0.0.0

    command: python app.py

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest tests.py